### ISSUE TITLE
AttributeError in _get_module_versions

### ISSUE THREAD

**Issue by vaaaaanquish** [m3dev/gokart#100]
```
ERROR: Error in event callback for 'event.core.start'
Traceback (most recent call last):
  File "python3.6/site-packages/luigi-2.8.9-py3.6.egg/luigi/task.py", line 276, in trigger_event
    callback(*args, **kwargs)
  File "python3.6/site-packages/gokart/task.py", line 281, in _dump_module_versions
    self.dump(self._get_module_versions(), self._get_module_versions_target())
  File "python3.6/site-packages/gokart/task.py", line 291, in _get_module_versions
    module_versions.append(f'{x}=={module.__version__.split(" ")[0]}')
AttributeError: 'tuple' object has no attribute 'split'
```

**Comment by vaaaaanquish** [comment]
`elasticsearch-py` 's version is tuple `(7, 0, 2)`
https://github.com/elastic/elasticsearch-py
