### ISSUE TITLE
[bug] ListTaskInstanceParameter does not move when not specific `requires` method

### ISSUE THREAD

**Issue by vaaaaanquish** [m3dev/gokart#195]
```python
import gokart

class Piyo(gokart.TaskOnKart):
    def run(self):
        self.dump('piyo')

class Hoge(gokart.TaskOnKart):
    hoge = gokart.ListTaskInstanceParameter()

    def run(self):
        hoge = self.load_data_frame('hoge')


gokart.build(Hoge(hoge=[Piyo(), Piyo()]))
```

```
Traceback (most recent call last):
  File "python3.7/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "python3.7/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "hoge.py", line 17, in run
    df = self.load_data_frame('hoge')
  File "python3.7/site-packages/gokart/task.py", line 236, in load_data_frame
    dfs = self.load(target=target)
  File "python3.7/site-packages/gokart/task.py", line 211, in load
    return _load(self._get_input_targets(target))
  File "python3.7/site-packages/gokart/task.py", line 276, in _get_input_targets
    return self.input()[target]
TypeError: list indices must be integers or slices, not str
```

**Comment by vaaaaanquish** [comment]
```
  File "python3.7/site-packages/gokart/task.py", line 276, in _get_input_targets
    return self.input()[target]
```
- `self.input()` is empty list
- nothing test for load : https://github.com/m3dev/gokart/blob/master/test/test_task_on_kart.py

**Comment by vaaaaanquish** [comment]
Not working.
```
class Hoge(gokart.TaskOnKart):
    hoge = gokart.ListTaskInstanceParameter()

    def run(self):
        hoge = self.load_data_frame('hoge')
```

Working:+1:
```
class Hoge(gokart.TaskOnKart):
    hoge = gokart.ListTaskInstanceParameter()

    def requires(self):
        return {'hoge': self.hoge}

    def run(self):
        hoge = self.load_data_frame('hoge')
```

**Comment by vaaaaanquish** [comment]
We must check List[TaskOnKart] here 

https://github.com/m3dev/gokart/blob/master/gokart/task.py#L79

**Comment by hirosassa** [comment]
Great work @vaaaaanquish for your detailed investigation and finding how to reproduce!
